In [7]:
import folium
import geojson
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pickle
import plotly.express as px
import plotly.graph_objects as go

from folium import plugins
from folium.plugins import HeatMap
from matplotlib.ticker import FuncFormatter, MultipleLocator
from scipy import stats

In [8]:
df_rent = pd.read_csv('data/mean_rents.csv')
df_rent.head()

,apartmentType,Borough,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,...,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,One bedroom,Manhattan,3075.00,3079.94,3054.43,3093.01,3127.09,3103.56,3054.76,3073.89,...,4283.44,4364.83,4454.01,4470.85,4516.99,4442.81,4386.88,4430.32,4443.38,4473.64
1,One bedroom,Queens,1689.88,1743.47,1750.00,1743.47,1745.59,1767.86,1753.19,1792.09,...,2502.11,2487.07,2542.06,2633.06,2641.88,2623.56,2599.39,2612.71,2617.73,2648.74
2,One bedroom,Brooklyn,1998.74,2032.57,2050.59,2089.89,2153.32,2171.10,2102.90,2127.21,...,3098.67,3225.65,3240.06,3367.32,3338.79,3391.18,3357.93,3315.09,3245.23,3316.77
3,One bedroom,Bronx,1343.75,1309.20,1400.50,1349.25,1387.30,1586.25,1366.61,1335.28,...,2206.75,2377.05,2340.50,2409.69,2376.83,2409.00,2521.44,2460.56,2383.40,2379.93
4,One bedroom,New York City,2850.00,2850.00,2850.00,2900.00,2900.00,2850.00,2750.00,2750.00,...,3500.00,3650.00,3659.00,3795.00,3850.00,3800.00,3700.00,3700.00,3695.00,3700.00

In [11]:
df_income = pd.read_csv('data/income_data.csv')
df_income.head()

,Unnamed: 0,Fiscal Year,Payroll Number,Agency Name,Last Name,First Name,Mid Init,Agency Start Date,Work Location Borough,Title Description,Leave Status as of June 30,Base Salary,Pay Basis,Regular Hours,Regular Gross Paid,OT Hours,Total OT Paid,Total Other Pay,Hourly Rate,Annual Salary Estimate
0,0,2025,67.0,ADMIN FOR CHILDREN'S SVCS,BLANCO,ELMER,S,02/04/2013,MANHATTAN,PROGRAM EVALUATOR,ACTIVE,95.897,per Annum,1.82,89.09713,0.0,0.00000,69941.00000,48.954467,101825.291429
1,1,2025,67.0,ADMIN FOR CHILDREN'S SVCS,OTERO,MATTHEW,P,02/22/2011,BRONX,CHILD PROTECTIVE SPECIALIST SUPERVISOR,ACTIVE,100.050,per Annum,1.82,96.95910,73.0,4.29175,6.93528,53.274231,110810.400000
2,2,2025,67.0,ADMIN FOR CHILDREN'S SVCS,PASCALL,DERRICK,F,02/22/2011,MANHATTAN,CHILD PROTECTIVE SPECIALIST SUPERVISOR,ACTIVE,106.346,per Annum,1.82,100.50313,0.0,0.00000,73241.00000,55.221500,114860.720000
3,3,2025,67.0,ADMIN FOR CHILDREN'S SVCS,DAUCHER,MEGHAN,B,02/28/2011,MANHATTAN,AGENCY ATTORNEY,ACTIVE,127.802,per Annum,1.82,82.89455,0.0,0.00000,9.80497,45.546456,94736.628571
4,4,2025,67.0,ADMIN FOR CHILDREN'S SVCS,JENKINS,LAMAR,T,06/03/2024,BRONX,SPECIAL OFFICER,ACTIVE,39.206,per Annum,2.08,37.76910,35475.0,10.00028,7.73753,18.158221,37769.100000

In [10]:
df_rent['apartmentType'].unique()

array(['One bedroom', 'Two bedrooms', 'Three plus bedrooms', 'Studio'],
      dtype=object)